### ISSUE TITLE
No Red Eclipse 2 specific assets

### ISSUE THREAD

**Issue by ghost** [redeclipse/promotional#4]
I still find the purpose of naming the steam version [red eclipse 2](https://store.steampowered.com/app/967460/Red_Eclipse_2/) confusing when none of the other assets on the website take on that name change. Would a v3 release result in a name change on the steam page to "Red Eclipse 3" ?

**Comment by acerspyro** [comment]
I actually at least partially agree, as to the eyes of Steam players, there was never a Red Eclipse 1.

The "Red Eclipse 2" naming scheme is only relevant to those who were present before the new version was released, which will be < 5% of the player in the coming year, with the game getting Steam exposure and whatnot.

I think Red Eclipse 2 should simply be internal, and instead rename the previous versions of Red Eclipse instead of confusing everyone.

**Comment by qreeves** [comment]
The "2" moniker has now been deprecated, as suggested.
